name: Expo CI - Web

on:
    push:
        branches: [main]
    pull_request:

jobs:
    build-web:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Instalar dependencias
              run: npm ci

            - name: Build web
              run: npx expo export --platform web

            - name: Lint y pruebas
              run: |
                  npm run lint
                  npm test
